// Generated by generate_events_zero_overhead.py
// Generated on: 2025-12-08 01:44:51
// DO NOT EDIT - Changes will be overwritten

#pragma once

#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>

/**
 * Zero-Overhead Event System
 * 
 * This file provides organized event bit definitions using
 * namespaces. There is ZERO runtime overhead - these compile
 * to the same constants as #define macros.
 * 
 * Usage:
 *   xEventGroupSetBits(handle, SystemEvents::State::BOILER_ENABLED);
 * 
 * Instead of:
 *   xEventGroupSetBits(handle, SYSTEM_STATE_BOILER_ENABLED_BIT);
 */

namespace SystemEvents {

    // ===== SystemState Events =====
    // Handle: xSystemStateEventGroup
    // System operational state tracking
    namespace SystemState {
        constexpr EventBits_t BOILER_ENABLED = (1UL << 0UL);  // Boiler system enabled
        constexpr EventBits_t BOILER_ON = (1UL << 1UL);  // Boiler currently on
        constexpr EventBits_t HEATING_ENABLED = (1UL << 2UL);  // Space heating enabled
        constexpr EventBits_t HEATING_ON = (1UL << 3UL);  // Space heating active
        constexpr EventBits_t WATER_ENABLED = (1UL << 4UL);  // Water heating enabled
        constexpr EventBits_t WATER_ON = (1UL << 5UL);  // Water heating active
        constexpr EventBits_t WATER_PRIORITY = (1UL << 6UL);  // Water has priority over heating
        constexpr EventBits_t BURNER_ON = (1UL << 7UL);  // Burner is running
        constexpr EventBits_t HEATING_PUMP_ON = (1UL << 8UL);  // Heating pump running
        constexpr EventBits_t WATER_PUMP_ON = (1UL << 9UL);  // Water pump running
        constexpr EventBits_t MQTT_ENABLED = (1UL << 12UL);  // MQTT communication enabled
        constexpr EventBits_t MQTT_COMMAND_ENABLED = (1UL << 13UL);  // MQTT commands enabled
        constexpr EventBits_t MQTT_REPORT_ENABLED = (1UL << 14UL);  // MQTT reporting enabled
        constexpr EventBits_t MQTT_OPERATIONAL = (1UL << 15UL);  // MQTT fully operational
        constexpr EventBits_t BURNER_OFF = (1UL << 16UL);  // Burner is off
        constexpr EventBits_t BURNER_HEATING_LOW = (1UL << 17UL);  // Burner on low for heating
        constexpr EventBits_t BURNER_HEATING_HIGH = (1UL << 18UL);  // Burner on high for heating
        constexpr EventBits_t BURNER_WATER_LOW = (1UL << 19UL);  // Burner on low for water
        constexpr EventBits_t BURNER_WATER_HIGH = (1UL << 20UL);  // Burner on high for water
        constexpr EventBits_t BURNER_ERROR = (1UL << 21UL);  // Burner in error state
        constexpr EventBits_t EMERGENCY_STOP = (1UL << 22UL);  // Emergency stop active
        constexpr EventBits_t WARNING = (1UL << 23UL);  // System warning active
        // Next free bit: 24

        // Useful combinations
        constexpr EventBits_t DEGRADED_MODE = WARNING;
    } // namespace SystemState

    // ===== Burner Events =====
    // Handle: xBurnerEventGroup
    // Burner-specific control and status
    namespace Burner {
        constexpr EventBits_t IDLE = (1UL << 0UL);  // Burner is idle
        constexpr EventBits_t STARTING = (1UL << 1UL);  // Burner is starting
        constexpr EventBits_t RUNNING = (1UL << 2UL);  // Burner is running
        constexpr EventBits_t STOPPING = (1UL << 3UL);  // Burner is stopping
        constexpr EventBits_t LOCKOUT = (1UL << 4UL);  // Burner in lockout state
        constexpr EventBits_t ENABLE = (1UL << 5UL);  // Burner enable signal
        constexpr EventBits_t LOW_POWER = (1UL << 6UL);  // Low power mode
        constexpr EventBits_t HIGH_POWER = (1UL << 7UL);  // High power mode
        constexpr EventBits_t PURGE = (1UL << 8UL);  // Purge cycle active
        constexpr EventBits_t FLAME_DETECTED = (1UL << 9UL);  // Flame detected
        constexpr EventBits_t TEMP_OK = (1UL << 10UL);  // Temperature within limits
        constexpr EventBits_t PRESSURE_OK = (1UL << 11UL);  // Pressure within limits
        constexpr EventBits_t SAFETY_OK = (1UL << 12UL);  // All safety checks OK
        constexpr EventBits_t ERROR_IGNITION = (1UL << 13UL);  // Ignition failure
        constexpr EventBits_t ERROR_FLAME_LOSS = (1UL << 14UL);  // Flame loss during operation
        constexpr EventBits_t ERROR_OVERHEAT = (1UL << 15UL);  // Overheat condition
        constexpr EventBits_t ERROR_PRESSURE = (1UL << 16UL);  // Pressure error
        constexpr EventBits_t FLAME_STATE_CHANGED = (1UL << 17UL);  // Flame state changed
        constexpr EventBits_t PRESSURE_CHANGED = (1UL << 18UL);  // Pressure sensor changed
        constexpr EventBits_t FLOW_CHANGED = (1UL << 19UL);  // Flow sensor changed
        constexpr EventBits_t SAFETY_EVENT = (1UL << 20UL);  // Any safety sensor changed
        constexpr EventBits_t STATE_TIMEOUT = (1UL << 21UL);  // State machine timeout occurred
        // Next free bit: 22

        // Useful combinations
        constexpr EventBits_t ANY_ERROR = ERROR_IGNITION | ERROR_FLAME_LOSS | ERROR_OVERHEAT | ERROR_PRESSURE;
    } // namespace Burner

    // ===== BurnerRequest Events =====
    // Handle: xBurnerRequestEventGroup
    // Burner demand coordination between heating and water
    namespace BurnerRequest {
        constexpr EventBits_t HEATING = (1UL << 0UL);  // Space heating requesting burner
        constexpr EventBits_t WATER = (1UL << 1UL);  // Water heating requesting burner
        constexpr EventBits_t POWER_LOW = (1UL << 3UL);  // Request low power mode
        constexpr EventBits_t POWER_HIGH = (1UL << 4UL);  // Request high power mode
        // M9: Moved CHANGED bits from 18-20 to 5-7 to avoid collision with TEMPERATURE_MASK (bits 16-23)
        constexpr EventBits_t CHANGED = (1UL << 5UL);  // Any request changed
        constexpr EventBits_t HEATING_CHANGED = (1UL << 6UL);  // Heating request changed
        constexpr EventBits_t WATER_CHANGED = (1UL << 7UL);  // Water request changed
        // Next free bit: 8 (bits 8-15 free, bits 16-23 reserved for temperature)

        // Special bit regions
        // Encoded target temperature (bits 16-23, do NOT use these bits for flags!)
        constexpr int TEMPERATURE_SHIFT = 16;
        constexpr int TEMPERATURE_BITS = 8;
        constexpr EventBits_t TEMPERATURE_MASK = ((1UL << TEMPERATURE_BITS) - 1) << TEMPERATURE_SHIFT;
        
        // Helper to encode/decode temperature
        constexpr EventBits_t encode_temperature(uint32_t value) {
            return (value & ((1UL << TEMPERATURE_BITS) - 1)) << TEMPERATURE_SHIFT;
        }
        constexpr uint32_t decode_temperature(EventBits_t bits) {
            return (bits >> TEMPERATURE_SHIFT) & ((1UL << TEMPERATURE_BITS) - 1);
        }

        // Useful combinations
        constexpr EventBits_t ANY_REQUEST = HEATING | WATER;
        constexpr EventBits_t POWER_BITS = POWER_LOW | POWER_HIGH;
        constexpr EventBits_t ALL_BITS = HEATING | WATER | POWER_LOW | POWER_HIGH | TEMPERATURE_MASK | CHANGED | HEATING_CHANGED | WATER_CHANGED;
        constexpr EventBits_t CHANGE_EVENT_BITS = HEATING_CHANGED | WATER_CHANGED | CHANGED;
    } // namespace BurnerRequest

    // ===== SensorUpdate Events =====
    // Handle: xSensorEventGroup
    // Temperature sensor update notifications
    namespace SensorUpdate {
        constexpr EventBits_t BOILER_OUTPUT = (1UL << 0UL);  // Boiler output temp updated
        constexpr EventBits_t BOILER_RETURN = (1UL << 1UL);  // Boiler return temp updated
        constexpr EventBits_t WATER_TANK = (1UL << 2UL);  // Water tank temp updated
        constexpr EventBits_t WATER_OUTPUT = (1UL << 3UL);  // Water output temp updated
        constexpr EventBits_t WATER_RETURN = (1UL << 4UL);  // Water return temp updated
        constexpr EventBits_t HEATING_RETURN = (1UL << 5UL);  // Heating return temp updated
        constexpr EventBits_t OUTSIDE = (1UL << 6UL);  // Outside temp updated
        constexpr EventBits_t INSIDE = (1UL << 7UL);  // Inside temp updated
        constexpr EventBits_t EXHAUST = (1UL << 8UL);  // Exhaust temp updated
        constexpr EventBits_t BOILER_OUTPUT_ERROR = (1UL << 10UL);  // Boiler output sensor error
        constexpr EventBits_t BOILER_RETURN_ERROR = (1UL << 11UL);  // Boiler return sensor error
        constexpr EventBits_t WATER_TANK_ERROR = (1UL << 12UL);  // Water tank sensor error
        constexpr EventBits_t WATER_OUTPUT_ERROR = (1UL << 13UL);  // Water output sensor error
        constexpr EventBits_t WATER_RETURN_ERROR = (1UL << 14UL);  // Water return sensor error
        constexpr EventBits_t HEATING_RETURN_ERROR = (1UL << 15UL);  // Heating return sensor error
        constexpr EventBits_t OUTSIDE_ERROR = (1UL << 16UL);  // Outside sensor error
        constexpr EventBits_t INSIDE_ERROR = (1UL << 17UL);  // Inside sensor error
        constexpr EventBits_t EXHAUST_ERROR = (1UL << 18UL);  // Exhaust sensor error
        constexpr EventBits_t DATA_ERROR = (1UL << 19UL);  // General sensor data error
        constexpr EventBits_t DATA_AVAILABLE = (1UL << 9UL);  // Sensor data available
        constexpr EventBits_t FIRST_READ_COMPLETE = (1UL << 23UL);  // First sensor read complete
        constexpr EventBits_t PRESSURE = (1UL << 20UL);  // System pressure updated
        constexpr EventBits_t PRESSURE_ERROR = (1UL << 21UL);  // Pressure sensor error
        // Next free bit: 24

        // Useful combinations
        constexpr EventBits_t ALL_TEMPS = BOILER_OUTPUT | BOILER_RETURN | WATER_TANK | WATER_OUTPUT | WATER_RETURN | HEATING_RETURN | OUTSIDE | INSIDE;
        constexpr EventBits_t CRITICAL_TEMPS = BOILER_OUTPUT | EXHAUST;
    } // namespace SensorUpdate

    // ===== Error Events =====
    // Handle: ERROR_NOTIFICATION
    // Error notification and recovery events
    namespace Error {
        constexpr EventBits_t SENSOR_FAILURE = (1UL << 0UL);  // Sensor has failed
        constexpr EventBits_t SENSOR_RESOLVED = (1UL << 1UL);  // Sensor error resolved
        constexpr EventBits_t WHEATER = (1UL << 2UL);  // Water heater error
        constexpr EventBits_t WHEATER_RESOLVED = (1UL << 3UL);  // Water heater error resolved
        constexpr EventBits_t BURNER = (1UL << 4UL);  // Burner error
        constexpr EventBits_t BURNER_RESOLVED = (1UL << 5UL);  // Burner error resolved
        constexpr EventBits_t PUMP = (1UL << 6UL);  // Pump error
        constexpr EventBits_t PUMP_RESOLVED = (1UL << 7UL);  // Pump error resolved
        constexpr EventBits_t GENERAL_SYSTEM = (1UL << 8UL);  // General system error
        constexpr EventBits_t GENERAL_SYSTEM_RESOLVED = (1UL << 9UL);  // General system error resolved
        constexpr EventBits_t COMMUNICATION = (1UL << 10UL);  // Communication error
        constexpr EventBits_t COMMUNICATION_RESOLVED = (1UL << 11UL);  // Communication error resolved
        constexpr EventBits_t MEMORY = (1UL << 12UL);  // Memory allocation error
        constexpr EventBits_t MEMORY_RESOLVED = (1UL << 13UL);  // Memory error resolved
        constexpr EventBits_t SAFETY = (1UL << 14UL);  // Safety check failed
        constexpr EventBits_t SAFETY_RESOLVED = (1UL << 15UL);  // Safety error resolved
        constexpr EventBits_t OVERHEAT = (1UL << 16UL);  // Overheating detected
        constexpr EventBits_t OVERHEAT_RESOLVED = (1UL << 17UL);  // Overheat resolved
        constexpr EventBits_t MODBUS = (1UL << 18UL);  // Modbus communication error
        constexpr EventBits_t RELAY = (1UL << 19UL);  // Relay control error
        constexpr EventBits_t NETWORK = (1UL << 20UL);  // Network error
        // Next free bit: 21

        // Useful combinations
        constexpr EventBits_t SENSOR = SENSOR_FAILURE;
        constexpr EventBits_t ANY_ACTIVE = SENSOR_FAILURE | WHEATER | BURNER | PUMP | GENERAL_SYSTEM | COMMUNICATION | MEMORY | SAFETY | OVERHEAT;
        constexpr EventBits_t ALL_RESOLVED = SENSOR_RESOLVED | WHEATER_RESOLVED | BURNER_RESOLVED | PUMP_RESOLVED | GENERAL_SYSTEM_RESOLVED | COMMUNICATION_RESOLVED | MEMORY_RESOLVED | SAFETY_RESOLVED | OVERHEAT_RESOLVED;
    } // namespace Error

    // ===== ControlRequest Events =====
    // Handle: xControlRequestEventGroup
    // Remote control requests from MQTT/scheduler
    namespace ControlRequest {
        constexpr EventBits_t BOILER_ENABLE = (1UL << 0UL);  // Enable boiler system
        constexpr EventBits_t BOILER_DISABLE = (1UL << 1UL);  // Disable boiler system
        constexpr EventBits_t HEATING_ENABLE = (1UL << 2UL);  // Enable heating
        constexpr EventBits_t HEATING_DISABLE = (1UL << 3UL);  // Disable heating
        constexpr EventBits_t HEATING_ON_OVERRIDE = (1UL << 4UL);  // Force heating on
        constexpr EventBits_t HEATING_OFF_OVERRIDE = (1UL << 5UL);  // Force heating off
        constexpr EventBits_t WATER_ENABLE = (1UL << 6UL);  // Enable water heating
        constexpr EventBits_t WATER_DISABLE = (1UL << 7UL);  // Disable water heating
        constexpr EventBits_t WATER_PRIORITY_ENABLE = (1UL << 8UL);  // Enable water priority
        constexpr EventBits_t WATER_PRIORITY_DISABLE = (1UL << 9UL);  // Disable water priority
        constexpr EventBits_t WATER_ON_OVERRIDE = (1UL << 10UL);  // Force water heating on
        constexpr EventBits_t WATER_OFF_OVERRIDE = (1UL << 11UL);  // Force water heating off
        constexpr EventBits_t MQTT_ENABLE = (1UL << 12UL);  // Enable MQTT
        constexpr EventBits_t MQTT_DISABLE = (1UL << 13UL);  // Disable MQTT
        constexpr EventBits_t MQTT_COMMAND_ENABLE = (1UL << 14UL);  // Enable MQTT commands
        constexpr EventBits_t MQTT_COMMAND_DISABLE = (1UL << 15UL);  // Disable MQTT commands
        constexpr EventBits_t MQTT_REPORT_ENABLE = (1UL << 16UL);  // Enable MQTT reporting
        constexpr EventBits_t MQTT_REPORT_DISABLE = (1UL << 17UL);  // Disable MQTT reporting
        constexpr EventBits_t WATER_PRIORITY_RELEASED = (1UL << 18UL);  // Water priority was released (notify heating)
        constexpr EventBits_t PID_SAVE = (1UL << 19UL);  // Save PID parameters
        constexpr EventBits_t SAVE_PARAMETERS = (1UL << 20UL);  // Save system parameters
        constexpr EventBits_t PID_AUTOTUNE = (1UL << 22UL);  // Start PID auto-tuning
        constexpr EventBits_t PID_AUTOTUNE_STOP = (1UL << 23UL);  // Stop PID auto-tuning
        // Next free bit: 21 (Note: bits 24-31 reserved by FreeRTOS!)
    } // namespace ControlRequest

    // ===== DeviceReady Events =====
    // Handle: deviceReadyEventGroup
    // Device initialization status tracking
    namespace DeviceReady {
        constexpr EventBits_t MB8ART_READY = (1UL << 0UL);  // MB8ART device initialized and ready
        constexpr EventBits_t MB8ART_ERROR = (1UL << 1UL);  // MB8ART initialization error
        constexpr EventBits_t RYN4_READY = (1UL << 2UL);  // RYN4 device initialized and ready
        constexpr EventBits_t RYN4_ERROR = (1UL << 3UL);  // RYN4 initialization error
        // Next free bit: 4

        // Useful combinations
        constexpr EventBits_t ALL_CRITICAL_READY = MB8ART_READY | RYN4_READY;
    } // namespace DeviceReady

    // ===== HeatingEvent Events =====
    // Handle: xHeatingEventGroup
    // Heating system control events
    namespace HeatingEvent {
        constexpr EventBits_t True = (1UL << 0UL);  // Heating system is turned on
        constexpr EventBits_t False = (1UL << 1UL);  // Heating system is turned off
        constexpr EventBits_t TEMP_LOW = (1UL << 2UL);  // Temperature below setpoint
        constexpr EventBits_t TEMP_HIGH = (1UL << 3UL);  // Temperature above setpoint
        constexpr EventBits_t ERROR = (1UL << 4UL);  // Heating system error occurred
        constexpr EventBits_t PUMP_ON = (1UL << 5UL);  // Heating pump turned on
        constexpr EventBits_t PUMP_OFF = (1UL << 6UL);  // Heating pump turned off
        constexpr EventBits_t DEMAND = (1UL << 7UL);  // Heat demand detected
        constexpr EventBits_t NO_DEMAND = (1UL << 8UL);  // No heat demand
        constexpr EventBits_t AUTOTUNE_START = (1UL << 9UL);  // Start PID auto-tuning
        constexpr EventBits_t AUTOTUNE_STOP = (1UL << 10UL);  // Stop PID auto-tuning
        constexpr EventBits_t AUTOTUNE_RUNNING = (1UL << 11UL);  // Auto-tuning in progress
        constexpr EventBits_t AUTOTUNE_COMPLETE = (1UL << 12UL);  // Auto-tuning completed
        constexpr EventBits_t AUTOTUNE_FAILED = (1UL << 13UL);  // Auto-tuning failed
        constexpr EventBits_t ERROR_SENSOR = (1UL << 16UL);  // Temperature sensor error
        constexpr EventBits_t ERROR_PUMP = (1UL << 17UL);  // Heating pump error
        constexpr EventBits_t ERROR_OVERHEAT = (1UL << 18UL);  // Overheating detected
        constexpr EventBits_t ERROR_TIMEOUT = (1UL << 19UL);  // Heating timeout
        // Next free bit: 20
    } // namespace HeatingEvent

    // ===== GeneralSystem Events =====
    // Handle: xGeneralSystemEventGroup
    // General system-wide status flags
    namespace GeneralSystem {
        constexpr EventBits_t STARTUP_COMPLETE = (1UL << 0UL);  // System startup completed
        constexpr EventBits_t NETWORK_READY = (1UL << 1UL);  // Network interface ready
        constexpr EventBits_t WIFI_CONNECTED = (1UL << 2UL);  // WiFi connected
        constexpr EventBits_t MQTT_CONNECTED = (1UL << 3UL);  // MQTT broker connected
        constexpr EventBits_t TIME_SYNCED = (1UL << 4UL);  // Time synchronized
        constexpr EventBits_t STORAGE_READY = (1UL << 5UL);  // Storage system ready
        constexpr EventBits_t SYSTEM_REBOOT = (1UL << 6UL);  // System reboot requested
        constexpr EventBits_t SENSOR_DEGRADED = (1UL << 7UL);  // Sensor operating in degraded mode
        constexpr EventBits_t MQTT_QUEUE_PRESSURE = (1UL << 8UL);  // MQTT queue under pressure
        constexpr EventBits_t MUTEX_CONTENTION = (1UL << 9UL);  // Mutex contention detected
        // Next free bit: 10
    } // namespace GeneralSystem

    // ===== RelayRequest Events =====
    // Handle: xRelayRequestEventGroup
    // Relay control requests
    namespace RelayRequest {
        constexpr EventBits_t HEATING_PUMP_ON = (1UL << 0UL);  // Request heating pump ON
        constexpr EventBits_t WATER_PUMP_ON = (1UL << 1UL);  // Request water pump ON
        constexpr EventBits_t HEATING_PUMP_OFF = (1UL << 2UL);  // Request heating pump OFF
        constexpr EventBits_t WATER_PUMP_OFF = (1UL << 3UL);  // Request water pump OFF
        constexpr EventBits_t BURNER_ENABLE = (1UL << 4UL);  // Request burner ON
        constexpr EventBits_t BURNER_DISABLE = (1UL << 5UL);  // Request burner OFF
        constexpr EventBits_t POWER_HALF = (1UL << 6UL);  // Request half power
        constexpr EventBits_t POWER_FULL = (1UL << 7UL);  // Request full power
        constexpr EventBits_t WATER_MODE_ON = (1UL << 8UL);  // Request water mode ON
        constexpr EventBits_t WATER_MODE_OFF = (1UL << 9UL);  // Request water mode OFF
        constexpr EventBits_t VALVE_OPEN = (1UL << 10UL);  // Request valve OPEN
        constexpr EventBits_t VALVE_CLOSE = (1UL << 11UL);  // Request valve CLOSE
        constexpr EventBits_t ALARM_ON = (1UL << 12UL);  // Request alarm ON
        constexpr EventBits_t ALARM_OFF = (1UL << 13UL);  // Request alarm OFF
        constexpr EventBits_t EMERGENCY_STOP = (1UL << 20UL);  // Emergency stop all relays
        constexpr EventBits_t UPDATE = (1UL << 21UL);  // Force relay state update
        // Next free bit: 22

        // Useful combinations
        constexpr EventBits_t PUMP_REQUESTS_MASK = HEATING_PUMP_ON | WATER_PUMP_ON | HEATING_PUMP_OFF | WATER_PUMP_OFF;
        constexpr EventBits_t BURNER_REQUESTS_MASK = BURNER_ENABLE | BURNER_DISABLE;
        constexpr EventBits_t POWER_REQUESTS_MASK = POWER_HALF | POWER_FULL;
        constexpr EventBits_t ALL_REQUESTS_MASK = (1UL << 22UL) - 1;
    } // namespace RelayRequest

    // ===== RelayStatus Events =====
    // Handle: xRelayStatusEventGroup
    // Relay status and feedback
    namespace RelayStatus {
        constexpr EventBits_t SYNCHRONIZED = (1UL << 0UL);  // Relay states synchronized
        constexpr EventBits_t COMM_OK = (1UL << 1UL);  // Communication OK
        constexpr EventBits_t COMM_ERROR = (1UL << 2UL);  // Communication error
        constexpr EventBits_t UPDATE_PENDING = (1UL << 3UL);  // Update pending
        // Next free bit: 4
    } // namespace RelayStatus

    // ===== RelayControl Events =====
    // Handle: xRelayEventGroup
    // Relay control requests and status
    namespace RelayControl {
        constexpr EventBits_t HEATING_PUMP_ON = (1UL << 0UL);  // Turn heating pump on
        constexpr EventBits_t HEATING_PUMP_OFF = (1UL << 1UL);  // Turn heating pump off
        constexpr EventBits_t WATER_PUMP_ON = (1UL << 2UL);  // Turn water pump on
        constexpr EventBits_t WATER_PUMP_OFF = (1UL << 3UL);  // Turn water pump off
        constexpr EventBits_t BURNER_ENABLE_ON = (1UL << 4UL);  // Enable burner
        constexpr EventBits_t BURNER_ENABLE_OFF = (1UL << 5UL);  // Disable burner
        constexpr EventBits_t WATER_MODE_ON = (1UL << 6UL);  // Switch to water mode
        constexpr EventBits_t WATER_MODE_OFF = (1UL << 7UL);  // Exit water mode
        constexpr EventBits_t POWER_BOOST_ON = (1UL << 8UL);  // Activate power boost (full power)
        constexpr EventBits_t POWER_BOOST_OFF = (1UL << 9UL);  // Deactivate power boost (half power)
        constexpr EventBits_t VALVE_OPEN = (1UL << 10UL);  // Open valve
        constexpr EventBits_t VALVE_CLOSE = (1UL << 11UL);  // Close valve
        constexpr EventBits_t ALARM_ON = (1UL << 12UL);  // Activate alarm
        constexpr EventBits_t ALARM_OFF = (1UL << 13UL);  // Deactivate alarm
        constexpr EventBits_t UPDATE_REQUIRED = (1UL << 14UL);  // Relay update needed
        constexpr EventBits_t UPDATE_COMPLETE = (1UL << 15UL);  // Relay update done
        constexpr EventBits_t DATA_AVAILABLE = (1UL << 16UL);  // Relay data available
        constexpr EventBits_t EMERGENCY_STOP = (1UL << 20UL);  // Emergency stop all
        constexpr EventBits_t FORCE_UPDATE = (1UL << 21UL);  // Force relay update
        // Next free bit: 22
    } // namespace RelayControl

} // namespace SystemEvents

// Event Group Handle Declarations
// These should be defined in your initialization code:
/*
extern EventGroupHandle_t xSystemStateEventGroup;
extern EventGroupHandle_t xBurnerEventGroup;
extern EventGroupHandle_t xBurnerRequestEventGroup;
extern EventGroupHandle_t xSensorEventGroup;
extern EventGroupHandle_t ERROR_NOTIFICATION;
extern EventGroupHandle_t xControlRequestEventGroup;
extern EventGroupHandle_t deviceReadyEventGroup;
extern EventGroupHandle_t xHeatingEventGroup;
extern EventGroupHandle_t xGeneralSystemEventGroup;
extern EventGroupHandle_t xRelayRequestEventGroup;
extern EventGroupHandle_t xRelayStatusEventGroup;
extern EventGroupHandle_t xRelayEventGroup;
*/

// Optional: Migration helper macros
// Uncomment these to help migrate from old #define style
/*
#define SYSTEMSTATE_BOILER_ENABLED_BIT SystemEvents::SystemState::BOILER_ENABLED
#define SYSTEMSTATE_BOILER_ON_BIT SystemEvents::SystemState::BOILER_ON
#define SYSTEMSTATE_HEATING_ENABLED_BIT SystemEvents::SystemState::HEATING_ENABLED
#define SYSTEMSTATE_HEATING_ON_BIT SystemEvents::SystemState::HEATING_ON
#define SYSTEMSTATE_WATER_ENABLED_BIT SystemEvents::SystemState::WATER_ENABLED
#define SYSTEMSTATE_WATER_ON_BIT SystemEvents::SystemState::WATER_ON
#define SYSTEMSTATE_WATER_PRIORITY_BIT SystemEvents::SystemState::WATER_PRIORITY
#define SYSTEMSTATE_BURNER_ON_BIT SystemEvents::SystemState::BURNER_ON
#define SYSTEMSTATE_HEATING_PUMP_ON_BIT SystemEvents::SystemState::HEATING_PUMP_ON
#define SYSTEMSTATE_WATER_PUMP_ON_BIT SystemEvents::SystemState::WATER_PUMP_ON
#define SYSTEMSTATE_MQTT_ENABLED_BIT SystemEvents::SystemState::MQTT_ENABLED
#define SYSTEMSTATE_MQTT_COMMAND_ENABLED_BIT SystemEvents::SystemState::MQTT_COMMAND_ENABLED
#define SYSTEMSTATE_MQTT_REPORT_ENABLED_BIT SystemEvents::SystemState::MQTT_REPORT_ENABLED
#define SYSTEMSTATE_MQTT_OPERATIONAL_BIT SystemEvents::SystemState::MQTT_OPERATIONAL
#define SYSTEMSTATE_BURNER_OFF_BIT SystemEvents::SystemState::BURNER_OFF
#define SYSTEMSTATE_BURNER_HEATING_LOW_BIT SystemEvents::SystemState::BURNER_HEATING_LOW
#define SYSTEMSTATE_BURNER_HEATING_HIGH_BIT SystemEvents::SystemState::BURNER_HEATING_HIGH
#define SYSTEMSTATE_BURNER_WATER_LOW_BIT SystemEvents::SystemState::BURNER_WATER_LOW
#define SYSTEMSTATE_BURNER_WATER_HIGH_BIT SystemEvents::SystemState::BURNER_WATER_HIGH
#define SYSTEMSTATE_BURNER_ERROR_BIT SystemEvents::SystemState::BURNER_ERROR
#define SYSTEMSTATE_EMERGENCY_STOP_BIT SystemEvents::SystemState::EMERGENCY_STOP
#define SYSTEMSTATE_WARNING_BIT SystemEvents::SystemState::WARNING
#define BURNER_IDLE_BIT SystemEvents::Burner::IDLE
#define BURNER_STARTING_BIT SystemEvents::Burner::STARTING
#define BURNER_RUNNING_BIT SystemEvents::Burner::RUNNING
#define BURNER_STOPPING_BIT SystemEvents::Burner::STOPPING
#define BURNER_LOCKOUT_BIT SystemEvents::Burner::LOCKOUT
#define BURNER_ENABLE_BIT SystemEvents::Burner::ENABLE
#define BURNER_LOW_POWER_BIT SystemEvents::Burner::LOW_POWER
#define BURNER_HIGH_POWER_BIT SystemEvents::Burner::HIGH_POWER
#define BURNER_PURGE_BIT SystemEvents::Burner::PURGE
#define BURNER_FLAME_DETECTED_BIT SystemEvents::Burner::FLAME_DETECTED
#define BURNER_TEMP_OK_BIT SystemEvents::Burner::TEMP_OK
#define BURNER_PRESSURE_OK_BIT SystemEvents::Burner::PRESSURE_OK
#define BURNER_SAFETY_OK_BIT SystemEvents::Burner::SAFETY_OK
#define BURNER_ERROR_IGNITION_BIT SystemEvents::Burner::ERROR_IGNITION
#define BURNER_ERROR_FLAME_LOSS_BIT SystemEvents::Burner::ERROR_FLAME_LOSS
#define BURNER_ERROR_OVERHEAT_BIT SystemEvents::Burner::ERROR_OVERHEAT
#define BURNER_ERROR_PRESSURE_BIT SystemEvents::Burner::ERROR_PRESSURE
#define BURNER_FLAME_STATE_CHANGED_BIT SystemEvents::Burner::FLAME_STATE_CHANGED
#define BURNER_PRESSURE_CHANGED_BIT SystemEvents::Burner::PRESSURE_CHANGED
#define BURNER_FLOW_CHANGED_BIT SystemEvents::Burner::FLOW_CHANGED
#define BURNER_SAFETY_EVENT_BIT SystemEvents::Burner::SAFETY_EVENT
#define BURNER_STATE_TIMEOUT_BIT SystemEvents::Burner::STATE_TIMEOUT
#define BURNERREQUEST_HEATING_BIT SystemEvents::BurnerRequest::HEATING
#define BURNERREQUEST_WATER_BIT SystemEvents::BurnerRequest::WATER
#define BURNERREQUEST_POWER_LOW_BIT SystemEvents::BurnerRequest::POWER_LOW
#define BURNERREQUEST_POWER_HIGH_BIT SystemEvents::BurnerRequest::POWER_HIGH
#define BURNERREQUEST_CHANGED_BIT SystemEvents::BurnerRequest::CHANGED
#define BURNERREQUEST_HEATING_CHANGED_BIT SystemEvents::BurnerRequest::HEATING_CHANGED
#define BURNERREQUEST_WATER_CHANGED_BIT SystemEvents::BurnerRequest::WATER_CHANGED
#define SENSORUPDATE_BOILER_OUTPUT_BIT SystemEvents::SensorUpdate::BOILER_OUTPUT
#define SENSORUPDATE_BOILER_RETURN_BIT SystemEvents::SensorUpdate::BOILER_RETURN
#define SENSORUPDATE_WATER_TANK_BIT SystemEvents::SensorUpdate::WATER_TANK
#define SENSORUPDATE_WATER_OUTPUT_BIT SystemEvents::SensorUpdate::WATER_OUTPUT
#define SENSORUPDATE_WATER_RETURN_BIT SystemEvents::SensorUpdate::WATER_RETURN
#define SENSORUPDATE_HEATING_RETURN_BIT SystemEvents::SensorUpdate::HEATING_RETURN
#define SENSORUPDATE_OUTSIDE_BIT SystemEvents::SensorUpdate::OUTSIDE
#define SENSORUPDATE_INSIDE_BIT SystemEvents::SensorUpdate::INSIDE
#define SENSORUPDATE_EXHAUST_BIT SystemEvents::SensorUpdate::EXHAUST
#define SENSORUPDATE_BOILER_OUTPUT_ERROR_BIT SystemEvents::SensorUpdate::BOILER_OUTPUT_ERROR
#define SENSORUPDATE_BOILER_RETURN_ERROR_BIT SystemEvents::SensorUpdate::BOILER_RETURN_ERROR
#define SENSORUPDATE_WATER_TANK_ERROR_BIT SystemEvents::SensorUpdate::WATER_TANK_ERROR
#define SENSORUPDATE_WATER_OUTPUT_ERROR_BIT SystemEvents::SensorUpdate::WATER_OUTPUT_ERROR
#define SENSORUPDATE_WATER_RETURN_ERROR_BIT SystemEvents::SensorUpdate::WATER_RETURN_ERROR
#define SENSORUPDATE_HEATING_RETURN_ERROR_BIT SystemEvents::SensorUpdate::HEATING_RETURN_ERROR
#define SENSORUPDATE_OUTSIDE_ERROR_BIT SystemEvents::SensorUpdate::OUTSIDE_ERROR
#define SENSORUPDATE_INSIDE_ERROR_BIT SystemEvents::SensorUpdate::INSIDE_ERROR
#define SENSORUPDATE_EXHAUST_ERROR_BIT SystemEvents::SensorUpdate::EXHAUST_ERROR
#define SENSORUPDATE_DATA_ERROR_BIT SystemEvents::SensorUpdate::DATA_ERROR
#define SENSORUPDATE_DATA_AVAILABLE_BIT SystemEvents::SensorUpdate::DATA_AVAILABLE
#define SENSORUPDATE_FIRST_READ_COMPLETE_BIT SystemEvents::SensorUpdate::FIRST_READ_COMPLETE
#define SENSORUPDATE_PRESSURE_BIT SystemEvents::SensorUpdate::PRESSURE
#define SENSORUPDATE_PRESSURE_ERROR_BIT SystemEvents::SensorUpdate::PRESSURE_ERROR
#define ERROR_SENSOR_FAILURE_BIT SystemEvents::Error::SENSOR_FAILURE
#define ERROR_SENSOR_RESOLVED_BIT SystemEvents::Error::SENSOR_RESOLVED
#define ERROR_WHEATER_BIT SystemEvents::Error::WHEATER
#define ERROR_WHEATER_RESOLVED_BIT SystemEvents::Error::WHEATER_RESOLVED
#define ERROR_BURNER_BIT SystemEvents::Error::BURNER
#define ERROR_BURNER_RESOLVED_BIT SystemEvents::Error::BURNER_RESOLVED
#define ERROR_PUMP_BIT SystemEvents::Error::PUMP
#define ERROR_PUMP_RESOLVED_BIT SystemEvents::Error::PUMP_RESOLVED
#define ERROR_GENERAL_SYSTEM_BIT SystemEvents::Error::GENERAL_SYSTEM
#define ERROR_GENERAL_SYSTEM_RESOLVED_BIT SystemEvents::Error::GENERAL_SYSTEM_RESOLVED
#define ERROR_COMMUNICATION_BIT SystemEvents::Error::COMMUNICATION
#define ERROR_COMMUNICATION_RESOLVED_BIT SystemEvents::Error::COMMUNICATION_RESOLVED
#define ERROR_MEMORY_BIT SystemEvents::Error::MEMORY
#define ERROR_MEMORY_RESOLVED_BIT SystemEvents::Error::MEMORY_RESOLVED
#define ERROR_SAFETY_BIT SystemEvents::Error::SAFETY
#define ERROR_SAFETY_RESOLVED_BIT SystemEvents::Error::SAFETY_RESOLVED
#define ERROR_OVERHEAT_BIT SystemEvents::Error::OVERHEAT
#define ERROR_OVERHEAT_RESOLVED_BIT SystemEvents::Error::OVERHEAT_RESOLVED
#define ERROR_MODBUS_BIT SystemEvents::Error::MODBUS
#define ERROR_RELAY_BIT SystemEvents::Error::RELAY
#define ERROR_NETWORK_BIT SystemEvents::Error::NETWORK
#define CONTROLREQUEST_BOILER_ENABLE_BIT SystemEvents::ControlRequest::BOILER_ENABLE
#define CONTROLREQUEST_BOILER_DISABLE_BIT SystemEvents::ControlRequest::BOILER_DISABLE
#define CONTROLREQUEST_HEATING_ENABLE_BIT SystemEvents::ControlRequest::HEATING_ENABLE
#define CONTROLREQUEST_HEATING_DISABLE_BIT SystemEvents::ControlRequest::HEATING_DISABLE
#define CONTROLREQUEST_HEATING_ON_OVERRIDE_BIT SystemEvents::ControlRequest::HEATING_ON_OVERRIDE
#define CONTROLREQUEST_HEATING_OFF_OVERRIDE_BIT SystemEvents::ControlRequest::HEATING_OFF_OVERRIDE
#define CONTROLREQUEST_WATER_ENABLE_BIT SystemEvents::ControlRequest::WATER_ENABLE
#define CONTROLREQUEST_WATER_DISABLE_BIT SystemEvents::ControlRequest::WATER_DISABLE
#define CONTROLREQUEST_WATER_PRIORITY_ENABLE_BIT SystemEvents::ControlRequest::WATER_PRIORITY_ENABLE
#define CONTROLREQUEST_WATER_PRIORITY_DISABLE_BIT SystemEvents::ControlRequest::WATER_PRIORITY_DISABLE
#define CONTROLREQUEST_WATER_ON_OVERRIDE_BIT SystemEvents::ControlRequest::WATER_ON_OVERRIDE
#define CONTROLREQUEST_WATER_OFF_OVERRIDE_BIT SystemEvents::ControlRequest::WATER_OFF_OVERRIDE
#define CONTROLREQUEST_MQTT_ENABLE_BIT SystemEvents::ControlRequest::MQTT_ENABLE
#define CONTROLREQUEST_MQTT_DISABLE_BIT SystemEvents::ControlRequest::MQTT_DISABLE
#define CONTROLREQUEST_MQTT_COMMAND_ENABLE_BIT SystemEvents::ControlRequest::MQTT_COMMAND_ENABLE
#define CONTROLREQUEST_MQTT_COMMAND_DISABLE_BIT SystemEvents::ControlRequest::MQTT_COMMAND_DISABLE
#define CONTROLREQUEST_MQTT_REPORT_ENABLE_BIT SystemEvents::ControlRequest::MQTT_REPORT_ENABLE
#define CONTROLREQUEST_MQTT_REPORT_DISABLE_BIT SystemEvents::ControlRequest::MQTT_REPORT_DISABLE
#define CONTROLREQUEST_WATER_PRIORITY_RELEASED_BIT SystemEvents::ControlRequest::WATER_PRIORITY_RELEASED
#define CONTROLREQUEST_PID_AUTOTUNE_BIT SystemEvents::ControlRequest::PID_AUTOTUNE
#define CONTROLREQUEST_PID_AUTOTUNE_STOP_BIT SystemEvents::ControlRequest::PID_AUTOTUNE_STOP
#define CONTROLREQUEST_PID_SAVE_BIT SystemEvents::ControlRequest::PID_SAVE
#define CONTROLREQUEST_SAVE_PARAMETERS_BIT SystemEvents::ControlRequest::SAVE_PARAMETERS
#define DEVICEREADY_MB8ART_READY_BIT SystemEvents::DeviceReady::MB8ART_READY
#define DEVICEREADY_MB8ART_ERROR_BIT SystemEvents::DeviceReady::MB8ART_ERROR
#define DEVICEREADY_RYN4_READY_BIT SystemEvents::DeviceReady::RYN4_READY
#define DEVICEREADY_RYN4_ERROR_BIT SystemEvents::DeviceReady::RYN4_ERROR
#define HEATINGEVENT_True_BIT SystemEvents::HeatingEvent::True
#define HEATINGEVENT_False_BIT SystemEvents::HeatingEvent::False
#define HEATINGEVENT_TEMP_LOW_BIT SystemEvents::HeatingEvent::TEMP_LOW
#define HEATINGEVENT_TEMP_HIGH_BIT SystemEvents::HeatingEvent::TEMP_HIGH
#define HEATINGEVENT_ERROR_BIT SystemEvents::HeatingEvent::ERROR
#define HEATINGEVENT_PUMP_ON_BIT SystemEvents::HeatingEvent::PUMP_ON
#define HEATINGEVENT_PUMP_OFF_BIT SystemEvents::HeatingEvent::PUMP_OFF
#define HEATINGEVENT_DEMAND_BIT SystemEvents::HeatingEvent::DEMAND
#define HEATINGEVENT_NO_DEMAND_BIT SystemEvents::HeatingEvent::NO_DEMAND
#define HEATINGEVENT_AUTOTUNE_START_BIT SystemEvents::HeatingEvent::AUTOTUNE_START
#define HEATINGEVENT_AUTOTUNE_STOP_BIT SystemEvents::HeatingEvent::AUTOTUNE_STOP
#define HEATINGEVENT_AUTOTUNE_RUNNING_BIT SystemEvents::HeatingEvent::AUTOTUNE_RUNNING
#define HEATINGEVENT_AUTOTUNE_COMPLETE_BIT SystemEvents::HeatingEvent::AUTOTUNE_COMPLETE
#define HEATINGEVENT_AUTOTUNE_FAILED_BIT SystemEvents::HeatingEvent::AUTOTUNE_FAILED
#define HEATINGEVENT_ERROR_SENSOR_BIT SystemEvents::HeatingEvent::ERROR_SENSOR
#define HEATINGEVENT_ERROR_PUMP_BIT SystemEvents::HeatingEvent::ERROR_PUMP
#define HEATINGEVENT_ERROR_OVERHEAT_BIT SystemEvents::HeatingEvent::ERROR_OVERHEAT
#define HEATINGEVENT_ERROR_TIMEOUT_BIT SystemEvents::HeatingEvent::ERROR_TIMEOUT
#define GENERALSYSTEM_STARTUP_COMPLETE_BIT SystemEvents::GeneralSystem::STARTUP_COMPLETE
#define GENERALSYSTEM_NETWORK_READY_BIT SystemEvents::GeneralSystem::NETWORK_READY
#define GENERALSYSTEM_WIFI_CONNECTED_BIT SystemEvents::GeneralSystem::WIFI_CONNECTED
#define GENERALSYSTEM_MQTT_CONNECTED_BIT SystemEvents::GeneralSystem::MQTT_CONNECTED
#define GENERALSYSTEM_TIME_SYNCED_BIT SystemEvents::GeneralSystem::TIME_SYNCED
#define GENERALSYSTEM_STORAGE_READY_BIT SystemEvents::GeneralSystem::STORAGE_READY
#define GENERALSYSTEM_SYSTEM_REBOOT_BIT SystemEvents::GeneralSystem::SYSTEM_REBOOT
#define GENERALSYSTEM_SENSOR_DEGRADED_BIT SystemEvents::GeneralSystem::SENSOR_DEGRADED
#define GENERALSYSTEM_MQTT_QUEUE_PRESSURE_BIT SystemEvents::GeneralSystem::MQTT_QUEUE_PRESSURE
#define GENERALSYSTEM_MUTEX_CONTENTION_BIT SystemEvents::GeneralSystem::MUTEX_CONTENTION
#define RELAYREQUEST_HEATING_PUMP_ON_BIT SystemEvents::RelayRequest::HEATING_PUMP_ON
#define RELAYREQUEST_WATER_PUMP_ON_BIT SystemEvents::RelayRequest::WATER_PUMP_ON
#define RELAYREQUEST_HEATING_PUMP_OFF_BIT SystemEvents::RelayRequest::HEATING_PUMP_OFF
#define RELAYREQUEST_WATER_PUMP_OFF_BIT SystemEvents::RelayRequest::WATER_PUMP_OFF
#define RELAYREQUEST_BURNER_ENABLE_BIT SystemEvents::RelayRequest::BURNER_ENABLE
#define RELAYREQUEST_BURNER_DISABLE_BIT SystemEvents::RelayRequest::BURNER_DISABLE
#define RELAYREQUEST_POWER_HALF_BIT SystemEvents::RelayRequest::POWER_HALF
#define RELAYREQUEST_POWER_FULL_BIT SystemEvents::RelayRequest::POWER_FULL
#define RELAYREQUEST_WATER_MODE_ON_BIT SystemEvents::RelayRequest::WATER_MODE_ON
#define RELAYREQUEST_WATER_MODE_OFF_BIT SystemEvents::RelayRequest::WATER_MODE_OFF
#define RELAYREQUEST_VALVE_OPEN_BIT SystemEvents::RelayRequest::VALVE_OPEN
#define RELAYREQUEST_VALVE_CLOSE_BIT SystemEvents::RelayRequest::VALVE_CLOSE
#define RELAYREQUEST_ALARM_ON_BIT SystemEvents::RelayRequest::ALARM_ON
#define RELAYREQUEST_ALARM_OFF_BIT SystemEvents::RelayRequest::ALARM_OFF
#define RELAYREQUEST_EMERGENCY_STOP_BIT SystemEvents::RelayRequest::EMERGENCY_STOP
#define RELAYREQUEST_UPDATE_BIT SystemEvents::RelayRequest::UPDATE
#define RELAYSTATUS_SYNCHRONIZED_BIT SystemEvents::RelayStatus::SYNCHRONIZED
#define RELAYSTATUS_COMM_OK_BIT SystemEvents::RelayStatus::COMM_OK
#define RELAYSTATUS_COMM_ERROR_BIT SystemEvents::RelayStatus::COMM_ERROR
#define RELAYSTATUS_UPDATE_PENDING_BIT SystemEvents::RelayStatus::UPDATE_PENDING
#define RELAYCONTROL_HEATING_PUMP_ON_BIT SystemEvents::RelayControl::HEATING_PUMP_ON
#define RELAYCONTROL_HEATING_PUMP_OFF_BIT SystemEvents::RelayControl::HEATING_PUMP_OFF
#define RELAYCONTROL_WATER_PUMP_ON_BIT SystemEvents::RelayControl::WATER_PUMP_ON
#define RELAYCONTROL_WATER_PUMP_OFF_BIT SystemEvents::RelayControl::WATER_PUMP_OFF
#define RELAYCONTROL_BURNER_ENABLE_ON_BIT SystemEvents::RelayControl::BURNER_ENABLE_ON
#define RELAYCONTROL_BURNER_ENABLE_OFF_BIT SystemEvents::RelayControl::BURNER_ENABLE_OFF
#define RELAYCONTROL_WATER_MODE_ON_BIT SystemEvents::RelayControl::WATER_MODE_ON
#define RELAYCONTROL_WATER_MODE_OFF_BIT SystemEvents::RelayControl::WATER_MODE_OFF
#define RELAYCONTROL_POWER_BOOST_ON_BIT SystemEvents::RelayControl::POWER_BOOST_ON
#define RELAYCONTROL_POWER_BOOST_OFF_BIT SystemEvents::RelayControl::POWER_BOOST_OFF
#define RELAYCONTROL_VALVE_OPEN_BIT SystemEvents::RelayControl::VALVE_OPEN
#define RELAYCONTROL_VALVE_CLOSE_BIT SystemEvents::RelayControl::VALVE_CLOSE
#define RELAYCONTROL_ALARM_ON_BIT SystemEvents::RelayControl::ALARM_ON
#define RELAYCONTROL_ALARM_OFF_BIT SystemEvents::RelayControl::ALARM_OFF
#define RELAYCONTROL_UPDATE_REQUIRED_BIT SystemEvents::RelayControl::UPDATE_REQUIRED
#define RELAYCONTROL_UPDATE_COMPLETE_BIT SystemEvents::RelayControl::UPDATE_COMPLETE
#define RELAYCONTROL_DATA_AVAILABLE_BIT SystemEvents::RelayControl::DATA_AVAILABLE
#define RELAYCONTROL_EMERGENCY_STOP_BIT SystemEvents::RelayControl::EMERGENCY_STOP
#define RELAYCONTROL_FORCE_UPDATE_BIT SystemEvents::RelayControl::FORCE_UPDATE
*/